# Loads up a bunch of default configs
# https://www.home-assistant.io/integrations/default_config/
default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.662831
  longitude: -122.128615
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

# This is needed with the Let's Encrypt add-on for DuckDNS add-on to work
# By using this, only the DuckDNS URL is expected to work when accessing HA,
# and not localhost or the static IP
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Weather prediction
sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

# Shopping list
shopping_list:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    mode: freedaily

ecobee:
  api_key: !secret ecobee_api_key

# Join
notify:
  - platform: joaoapps_join
    api_key: !secret join_api_key
    device_id: group.all
    name: Join
joaoapps_join:
  - name: All Devices
    device_id: group.all
    api_key: !secret join_api_key

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
