homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.662831
  longitude: -122.128615
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: 59c792eb-d182-499d-aa66-405401401ec3.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

panel_iframe:
  nodered:
    title: Node-RED Flows
    icon: mdi:nodejs
    url: https://59c792eb-d182-499d-aa66-405401401ec3.duckdns.org:1880

  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://59c792eb-d182-499d-aa66-405401401ec3.duckdns.org:3218

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

ecobee:
  api_key: !secret ecobee_api_key

# Join
notify:
  - platform: joaoapps_join
    api_key: !secret join_api_key
    device_id: group.all
    name: Join
joaoapps_join:
  - name: All Devices
    device_id: group.all
    api_key: !secret join_api_key
